# Generated by Django 5.2.7 on 2025-10-09 15:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-friendly type name', max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Two-letter ISO code, e.g., 'PT', 'BR'", max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Use a 2-letter country code.')])),
                ('currency_code', models.CharField(help_text="Three-letter currency code, e.g., 'EUR', 'BRL'", max_length=3, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}$', 'Use a 3-letter currency code.')])),
                ('currency_name', models.CharField(blank=True, help_text="Optional currency name, e.g., 'Euro', 'Brazilian Real'", max_length=60)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(help_text='Bank or provider name', max_length=120)),
                ('initial_balance', models.DecimalField(decimal_places=2, help_text='Initial balance at account creation', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('balance', models.DecimalField(decimal_places=2, help_text='Current balance; defaults to initial on create', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('active', models.BooleanField(default=True, help_text='Whether the account is active')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When the account was deactivated', null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accounttype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.country')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['bank', 'id'],
                'indexes': [models.Index(fields=['bank'], name='accounts_ac_bank_4bcf2c_idx'), models.Index(fields=['active'], name='accounts_ac_active_a5d2fe_idx')],
            },
        ),
    ]
