# Generated by Django 5.2.7 on 2025-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, help_text="Currency symbol, e.g., '€', 'R$', '$'", max_length=5),
        ),
    ]
