# Generated by Django 5.2.7 on 2025-10-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_country_currency_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default=None, help_text='Owner user that created/owns this account', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner'], name='accounts_ac_owner_i_e99d96_idx'),
        ),
    ]
