# Generated by Django 5.2.7 on 2025-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date the transaction was actually completed/paid', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="e.g., Bootstrap Icons class like 'bi-house-fill' See more in https://icons.getbootstrap.com/", max_length=50),
        ),
    ]
