# Generated by Django 5.2.7 on 2025-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_installment_number_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The value in the destination account's currency", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate applied at the time of the transfer', max_digits=18, null=True),
        ),
    ]
