# Generated by Django 5.2.7 on 2025-10-16 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_installment_number_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The value in the destination account's currency", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate applied at the time of the transfer', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="e.g., Bootstrap Icons class like 'bi-house-fill'", max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Due date or date of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='In the currency of the origin account for expenses/transfers, or destination for incomes', max_digits=14),
        ),
    ]
